##### modify 
name: Docker Image CI

on:
  push:
    branches: ["dev3-setting"]
  pull_request:
    branches: ["main"]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build front/. --file front/Dockerfile --tag frontend/yoonjihyeon:$(date +%s)
 
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
       username: ${{secrets.DOCKERHUB_USERNAME}}
       password: ${{secrets.DOCKERHUB_TOKEN}}
       build_args: REACT_APP_HOST_URL=http://localhost:8080/api
    - name: build and release to DockerHub
      env:
       NAME: yoonjihyeon
       REPO: frontend
      run: |
       docker build -t $REPO front/. 
       docker tag $REPO:latest $NAME/$REPO:latest 
       docker push $NAME/$REPO:latest

