name: CI/CD with Docker and Java

on:
  push:
    paths:
      - 'back/**'  # 백엔드 디렉토리 변경 감지
      - 'front/**' # 프론트엔드 디렉토리 변경 감지
    branches:
      - main
  pull_request:
    paths:
      - 'back/**'
      - 'front/**'
    branches:
      - main

jobs:
  build-backend:
    if: ${{ github.event_name == 'push' && contains(github.event.head_commit.modified, 'back/') }}
    # 또는: if: ${{ github.event_name == 'push' && github.event.head_commit.modified | contains('back/') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Copy Secret
        env:
          OCCUPY_SECRET: ${{ secrets.OCCUPY_SECRET }}
          OCCUPY_SECRET_DIR: back/src/main/resources
          OCCUPY_SECRET_TEST_DIR: back/src/test/java/com/fcc/PureSync
          OCCUPY_SECRET_DIR_FILE_NAME: application-secret.properties
        run: |
          echo $OCCUPY_SECRET | base64 --decode > $OCCUPY_SECRET_DIR/$OCCUPY_SECRET_DIR_FILE_NAME && 
          echo $OCCUPY_SECRET | base64 --decode > $OCCUPY_SECRET_TEST_DIR/$OCCUPY_SECRET_DIR_FILE_NAME

      - name: Build Backend with Gradle
        run: |
          cd back
          chmod +x gradlew
          ./gradlew build

  build-frontend-and-release:
    if: ${{ github.event_name == 'push' && contains(github.event.head_commit.modified, 'front/') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Frontend
        run: |
          cd front
          npm install
          CI='false' npm run build

      - name: Login to DockerHub and Build Image
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          build_args: REACT_APP_HOST_URL=http://192.168.56.1:8080/api

      - name: Build and release to DockerHub
        env:
          NAME: yoonjihyeon
          REPO: front
        run: |
          docker build -t $REPO --file front/Dockerfile .
          docker tag $REPO:latest $NAME/$REPO:latest
          docker push $NAME/$REPO:latest
